# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.3
  aws-cli: circleci/aws-cli@0.1.13

executors:
  node-executor:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/project

jobs:
  install:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - persist_to_workspace:
          root: /home/circleci
          paths: project

  lint_test_coverage:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/

      # - run:
      #     name: Run Linter
      #     command: yarn run lint

      - run:
          name: Run Tests
          command: yarn run test

      # - run:
      #     name: Report to CodeCov
      #     command: npx codecov@3

      - persist_to_workspace:
          root: /home/circleci
          paths: project

  build:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Build Client
          command: yarn run build

      - persist_to_workspace:
          root: /home/circleci
          paths: project/build

  deploy:
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: ~/

      - aws-s3/sync:
          from: ~/project/build
          to: 's3://chatbot-enrollment'

  flush_cache:
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: Invalidate Index
          command: aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFORMATION_DISTRIBUTION_ID} --paths /index.html

workflows:
  build_test_deploy:
    jobs:
      - install
      - lint_test_coverage:
          requires:
            - install
      - build:
          requires:
            - lint_test_coverage
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - flush_cache:
          requires:
            - deploy
